import html2pdf from 'html2pdf.js';

type PdfOrientation = 'portrait' | 'landscape';

interface ExportPdfOptions {
  filename: string;
  orientation?: PdfOrientation;
  /**
   * If true, renders the element into a fixed A4-sized container before export.
   * This helps prevent layout-dependent clipping on wide dashboards.
   */
  renderAtA4Size?: boolean;
}

function pxForA4Width(orientation: PdfOrientation): number {
  // Approx A4 at 96dpi:
  // - portrait width: 8.27in * 96 ≈ 794px
  // - landscape width: 11.69in * 96 ≈ 1123px
  return orientation === 'landscape' ? 1123 : 794;
}

function pxForA4Height(orientation: PdfOrientation): number {
  // Approx A4 at 96dpi:
  // - portrait height: 11.69in * 96 ≈ 1123px
  // - landscape height: 8.27in * 96 ≈ 794px
  return orientation === 'landscape' ? 794 : 1123;
}

export async function exportElementToPdfA4(element: HTMLElement, options: ExportPdfOptions): Promise<void> {
  // Default to landscape since dashboards are expected A4 yatay.
  const orientation = options.orientation ?? 'landscape';
  const fixedWidthPx = pxForA4Width(orientation);
  const fixedHeightPx = pxForA4Height(orientation);

  // Tag the element so we can reliably find it inside html2canvas's cloned document.
  const exportId = `pdf-export-${Date.now()}-${Math.random().toString(16).slice(2)}`;
  element.setAttribute('data-pdf-export-id', exportId);

  try {
    const opt = {
      // Keep margins modest so "1 page overview + 1 page details" fits in A4 landscape.
      margin: [6, 6, 6, 6],
      filename: options.filename,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: {
        scale: 2,
        useCORS: true,
        logging: false,
        backgroundColor: '#ffffff',
        // When exporting dashboards, we want a deterministic layout width.
        // Using html2canvas's cloned DOM is more reliable than mounting far off-screen
        // (which can produce blank captures on some browsers).
        windowWidth: options.renderAtA4Size ? fixedWidthPx + 32 : undefined,
        onclone: (doc: Document) => {
          if (!options.renderAtA4Size) return;
          const clonedTarget = doc.querySelector<HTMLElement>(`[data-pdf-export-id="${exportId}"]`);
          if (!clonedTarget) return;

          // Wrap in a fixed-width white container (A4 width @ ~96dpi).
          const wrapper = doc.createElement('div');
          wrapper.style.width = `${fixedWidthPx}px`;
          wrapper.style.background = '#ffffff';
          wrapper.style.padding = '16px';
          wrapper.style.boxSizing = 'border-box';
          wrapper.style.position = 'relative';

          // Ensure the dashboard doesn't clip its own content.
          clonedTarget.style.maxHeight = 'none';
          clonedTarget.style.overflow = 'visible';
          clonedTarget.style.width = '100%';
          clonedTarget.style.maxWidth = 'none';

          const parent = clonedTarget.parentElement;
          if (parent) {
            parent.replaceChild(wrapper, clonedTarget);
            wrapper.appendChild(clonedTarget);
          }

          // Optional watermark (recommended): bottom-right label
          const watermark = doc.createElement('div');
          watermark.textContent = 'Generated by FinOps AI Studio';
          watermark.style.position = 'absolute';
          watermark.style.right = '12px';
          watermark.style.bottom = '10px';
          watermark.style.fontSize = '10px';
          watermark.style.fontFamily = 'system-ui, -apple-system, Segoe UI, Roboto, Arial, sans-serif';
          watermark.style.color = '#6b7280'; // gray-500
          watermark.style.opacity = '0.9';
          wrapper.appendChild(watermark);

          // Optional: Fit overview blocks to a single page height.
          // Any element marked with `data-pdf-fit="one-page"` will be scaled down
          // (uniform scale) so it doesn't spill to extra pages.
          //
          // This is how we keep "çoklu grafik" overview pages to a single A4 page.
          const fitEls = doc.querySelectorAll<HTMLElement>('[data-pdf-fit="one-page"]');
          fitEls.forEach((fitEl) => {
            // Ensure natural size is measurable
            fitEl.style.transform = 'none';
            fitEl.style.transformOrigin = 'top left';

            const padding = 32; // wrapper padding top+bottom (16px each)
            const available = Math.max(200, fixedHeightPx - padding);
            const contentHeight = Math.max(fitEl.scrollHeight, fitEl.getBoundingClientRect().height);

            if (contentHeight > 0) {
              const scale = Math.min(1, available / contentHeight);
              if (scale < 1) {
                fitEl.style.transformOrigin = 'top left';
                fitEl.style.transform = `scale(${scale})`;
                // Prevent layout collapse after scaling
                fitEl.style.width = `${Math.round(100 / scale)}%`;
              }
            }
          });

          // Stop animations/transitions to avoid capturing mid-frame.
          const all = doc.querySelectorAll<HTMLElement>('*');
          all.forEach((el) => {
            el.style.animation = 'none';
            el.style.transition = 'none';
          });
        },
      },
      jsPDF: { unit: 'mm', format: 'a4', orientation },
      // Avoid breaking key blocks (cards/charts) across pages where possible.
      pagebreak: { mode: ['css', 'legacy'], avoid: ['.pdf-avoid-break'] },
    };

    await html2pdf().set(opt).from(element).save();
  } finally {
    element.removeAttribute('data-pdf-export-id');
  }
}

